### ISSUE TITLE
Can't broadcast (1260, 1080) -> (864, 444)

### ISSUE THREAD

**Issue by nicodalse** [aria-tools/ARIA-tools#157]
I encountered this error with 2 different computers and 2 different sizes. 
(I have the PR #156 version)
Before I used: 

`ariaTSsetup.py -f 'products/S1*.nc' -l 'all' -nt 'all' -b '39.45 40.5 -124.1 -123.2' -d Download -m Download`

Then when I try to use this command:

`$ prep_aria.py -w mintpy -s stack/ -d DEM/SRTM_3arcsec.dem -i incidenceAngle/20150617_20150524.vrt -a azimuthAngle/20150617_20150524.vrt --water-mask mask/watermask.msk `

I get this error:
```
extract metadata from /Users/seno/Documents/35_update/stack/unwrapStack.vrt
--------------------------------------------------
create HDF5 file /Users/seno/Documents/35_update/mintpy/inputs/geometryGeo.h5 with w mode
create dataset: height                    of <class 'numpy.float32'>   in size of (864, 444)
create dataset: incidenceAngle            of <class 'numpy.float32'>   in size of (864, 444)
create dataset: slantRangeDistance        of <class 'numpy.float32'>   in size of (864, 444)
create dataset: azimuthAngle              of <class 'numpy.float32'>   in size of (864, 444)
create dataset: waterMask                 of <class 'numpy.bool_'>     in size of (864, 444)
close HDF5 file /Users/seno/Documents/35_update/mintpy/inputs/geometryGeo.h5
--------------------------------------------------
writing data to HDF5 file /Users/seno/Documents/35_update/mintpy/inputs/geometryGeo.h5 with a mode ...
Traceback (most recent call last):
  File "/Users/seno/python/MintPy/mintpy/prep_aria.py", line 407, in <module>
    main()
  File "/Users/seno/python/MintPy/mintpy/prep_aria.py", line 377, in main
    write_geometry(geom_file,
  File "/Users/seno/python/MintPy/mintpy/prep_aria.py", line 225, in write_geometry
    h5['height'][:,:] = data
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/seno/opt/anaconda3/envs/ARIA-tools/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 707, in __setitem__
    for fspace in selection.broadcast(mshape):
  File "/Users/seno/opt/anaconda3/envs/ARIA-tools/lib/python3.8/site-packages/h5py/_hl/selections.py", line 299, in broadcast
    raise TypeError("Can't broadcast %s -> %s" % (target_shape, self.mshape))
TypeError: Can't broadcast (1260, 1080) -> (864, 444)
```
I can pass it only if I use the coordinates in order to have the exact box size (864, 444), which I believe is related with the firs processing I do with the following command:

`ariaTSsetup.py -f 'products/S1*.nc' -l 'all' -nt 'all' -b '39.7 40.42 -123.77 -123.40' -d Download -m Download`

These coordinates correspond to the size of the box required.

**Comment by dbekaert** [comment]
@nicodalse can you provide an example for us to replicate?
e.g. which files should we download to test the ariaTSsetup upon?
Ideally not a full time-series of files but a subset to illustrate the problem.

**Comment by nicodalse** [comment]
@dbekaert Yes! Thanks for your reply.
I used the Track 35a with the following command:

`ariaDownload.py --track 035 --bbox "39.3 40.7 -124.15 -123.0" -o download`

then I worked on a smaller box:

`ariaTSsetup.py -f 'products/S1*.nc' -l 'all' -nt 'all' -b '39.45 40.5 -124.1 -123.2' -d Download -m Download`

then:

`$ prep_aria.py -w mintpy -s stack/ -d DEM/SRTM_3arcsec.dem -i incidenceAngle/20150617_20150524.vrt -a azimuthAngle/20150617_20150524.vrt --water-mask mask/watermask.msk`

And here I have the previus error:TypeError:` Can't broadcast (1260, 1080) -> (864, 444)`

N.B. If I put a difference between Sud and North = 0.72 and between West and East = 0.37 I can pass the previous error because the box size is exactly: (864,444).

I think this size comes from my first `ariaTSsetup.py`  after the installation, where I used the following coordinates`'39.7 40.42 -123.77 -123.40'` size=(864,444).
I think this because I found the same problem on the Linux Server, but with smaller size (96,48).

**Comment by dbekaert** [comment]
@sssangha made some more fixes on this issue that have been merged into dev.

**Comment by sssangha** [comment]
@nicodalse I believe that this issue has been addressed. Please confirm by re-running your stack. 

As a quick test, you may run this on just one pair. E.g. ```ariaTSsetup.py -f 'products/S1*.nc' -l 'all' -nt 'all' -b '39.45 40.5 -124.1 -123.2' -d Download -m Download```

**Comment by nicodalse** [comment]
@sssangha Thank you very much, unfortunately after that command I found the same problem at the next step:
 ```
(ARIA-tools) LMC-047239:35_update seno$ prep_aria.py -w mintpy -s stack/ -d DEM/SRTM_3arcsec.dem -i incidenceAngle/20150617_20150524.vrt -a azimuthAngle/20150617_20150524.vrt --water-mask mask/watermask.msk
extract metadata from /Users/seno/Documents/35_update/stack/unwrapStack.vrt
--------------------------------------------------
create HDF5 file /Users/seno/Documents/35_update/mintpy/inputs/geometryGeo.h5 with w mode
create dataset: height                    of <class 'numpy.float32'>   in size of (864, 444)
create dataset: incidenceAngle            of <class 'numpy.float32'>   in size of (864, 444)
create dataset: slantRangeDistance        of <class 'numpy.float32'>   in size of (864, 444)
create dataset: azimuthAngle              of <class 'numpy.float32'>   in size of (864, 444)
create dataset: waterMask                 of <class 'numpy.bool_'>     in size of (864, 444)
close HDF5 file /Users/seno/Documents/35_update/mintpy/inputs/geometryGeo.h5
--------------------------------------------------
writing data to HDF5 file /Users/seno/Documents/35_update/mintpy/inputs/geometryGeo.h5 with a mode ...
Traceback (most recent call last):
  File "/Users/seno/python/MintPy/mintpy/prep_aria.py", line 407, in <module>
    main()
  File "/Users/seno/python/MintPy/mintpy/prep_aria.py", line 377, in main
    write_geometry(geom_file,
  File "/Users/seno/python/MintPy/mintpy/prep_aria.py", line 225, in write_geometry
    h5['height'][:,:] = data
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/seno/opt/anaconda3/envs/ARIA-tools/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 707, in __setitem__
    for fspace in selection.broadcast(mshape):
  File "/Users/seno/opt/anaconda3/envs/ARIA-tools/lib/python3.8/site-packages/h5py/_hl/selections.py", line 299, in broadcast
    raise TypeError("Can't broadcast %s -> %s" % (target_shape, self.mshape))
TypeError: Can't broadcast (1260, 1080) -> (864, 444)
```
(I've installed last PR and I also did a new Conda environment)

**Comment by bbuzzanga** [comment]
Hi Nicole, 

I haven’t tried to reproduce your specific error, but I do notice that you’re using an old version of MintPy (the -w option is no more).
It’s unlikely that this will solve the problem but shouldn’t take long to fix.

- Brett

**Comment by nicodalse** [comment]
Hi Brett,

Thanks for the tip, but the update doesn't fix the error. Now the command to reproduce it, is:
`$ prep_aria.py -s stack/ -d DEM/SRTM_3arcsec.dem -i incidenceAngle/20150617_20150524.vrt -a azimuthAngle/20150617_20150524.vrt --water-mask mask/watermask.msk`

**Comment by ehavazli** [comment]
Hi @nicodalse ,

I wasn't able to reproduce your error. I used the commands you posted:

```
ariaDownload.py --track 035 --bbox "39.3 40.7 -124.15 -123.0" -o download

ariaTSsetup.py -f 'products/S1*.nc' -l 'all' -nt 'all' -b '39.45 40.5 -124.1 -123.2' -d Download -m Download

prep_aria.py -s ./stack/ -d ./DEM/SRTM_3arcsec.dem -i ./incidenceAngle/20150617_20150524.vrt -a ./azimuthAngle/20150617_20150524.vrt --water-mask ./mask/watermask.msk
```
I would recommend deleting all the folders ariaTSsetup.py creates under your work directory and rerunning it (including specifically the DEM considering the fact that the error is thrown when writing the height information to geometryGeo.h5).

Before going forward with the prep_aria.py, I recommend you use:
```
ariaPlot.py -f './products/*.nc' -plotall
```
and take a look at the lat_extents.eps


![lat_extents](https://user-images.githubusercontent.com/6526589/84086008-b5012e80-a99b-11ea-9b38-6ec4d25a21d2.jpg)

it seems like some of the products I downloaded doesn't cover your area of interest completely and you may want to subset products using another measure (e.g. -mo option in ariaTSsetup.py):

```
 -mo MINIMUMOVERLAP, --minimumOverlap MINIMUMOVERLAP
                        Minimum km² area of overlap of scenes wrt specified bounding box. Default 0.0081 = 0.0081km² = area of single pixel at standard 90m resolution"
```

**Comment by nicodalse** [comment]
Hi @ehavazli ,

Thank you very much, you solved my problem. You are right, you wasn't able to reproduce my problem because you should run before:
`ariaTSsetup.py -f 'products/S1*.nc' -l 'all' -nt 'all' -b 'different coordinates' -d Download -m Download`
I simply ran again the command but in a new folder and everything gone right. I thought the DEM's files and the geometryGeo.h5 they would be overwritten if I change coordinates.
Thanks!
